name: build

on:
  push:
    branches:
      - master
      - actions
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
      - name: Build
        run: ./mvnw package